// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	parking "parking-lot-cli/parking"
	mock "github.com/stretchr/testify/mock"
)

// ObserverSubscriber is an autogenerated mock type for the ObserverSubscriber type
type ObserverSubscriber struct {
	mock.Mock
}

// Update provides a mock function with given fields: _a0
func (_m *ObserverSubscriber) Update(_a0 *parking.ParkingLot) {
	_m.Called(_a0)
}

// UpdateParkNowAvailable provides a mock function with given fields: _a0
func (_m *ObserverSubscriber) UpdateParkNowAvailable(_a0 *parking.ParkingLot) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewObserverSubscriber interface {
	mock.TestingT
	Cleanup(func())
}

// NewObserverSubscriber creates a new instance of ObserverSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewObserverSubscriber(t mockConstructorTestingTNewObserverSubscriber) *ObserverSubscriber {
	mock := &ObserverSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
